name: CI Backend Lint
on:
  push:
    paths:
      - 'merchrisk-engine/backend/**'
    branches:
      - dev
  pull_request:
    paths:
      - 'merchrisk-engine/backend/**'

jobs:
  lint-backend:
    uses: ./.github/workflows/lint-reusable.yml
    with:
      node-version: '22.16.0'
      run-lint: true
      app-path: './backend'
  test-backend:
    uses: ./.github/workflows/test-re-usable.yml
    with:
      node-version: '22.16.0'
      run-tests: true
      app-path: './backend'
