name: Format Reusable Workflows

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '22.16.0'
      run-format:
        description: 'Whether to run format'
        required: false
        type: boolean
        default: true
      app-path:
        description: 'Path to the application'
        required: true
        type: string
        #default: './merchrisk-engine/backend'


jobs:
  format:
    if: ${{ inputs.run-format }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Install dependencies
        working-directory: ${{ inputs['app-path'] }}
        run: |
          npm ci

      - name: Run lint
        run: |
          cd ${{ inputs['app-path'] }}
          ls -al node_modules
          npm run fmt